//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guante_View
    {
        public int idGuante { get; set; }
        public string ImagenGuante { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Talla { get; set; }
        public string NombreCategoria { get; set; }
        public string NombreColores { get; set; }
        public string NombreMarca { get; set; }
        public string NombreModelo { get; set; }
    }
}
